#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Serviço – Aplicar Plano de Mudanças (Estrutura Dinâmica)❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

from __future__ import annotations

import os
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from models.struc_anal.struc_anal_models import PlannedFileCreation, PlannedFileSection
from utils.log_manager import add_log
from utils.logger import log_workflow
from utils.path_validation import is_path_under_base, sanitize_relative_path
from storage.database import database_c3 as db_c3

#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Inferência Dinâmica de Padrão de Projeto❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━


def _infer_folder_pattern(directory: Path) -> str:
    """Detecta se o diretório é flat ou module-style."""
    if not directory.exists():
        return "module"

    subfolders = [f for f in directory.iterdir() if f.is_dir()]
    python_files = [f for f in directory.iterdir() if f.is_file() and f.suffix == ".py"]

    for sf in subfolders:
        if (sf / f"{sf.name}.py").exists():
            return "module"

    if python_files and not subfolders:
        return "flat"

    return "module"


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Materialização de Caminho (evita duplicação)❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━


def _materialize_dynamic_path(project_root: Path, relative_path: str) -> Path:
    """
    Evita gerar dois routers:
      • se o caminho já contém '/routers/' OU termina com '_router.py',
        mantemos exatamente o path fornecido.
    Para os demais papéis continua a lógica anterior.
    """
    rel = Path(relative_path.lstrip("/\\"))
    if "/routers/" in rel.as_posix() or rel.name.endswith("_router.py"):
        # ❶  regra nova – nunca duplica routers
        return project_root / rel

    parent_dir = project_root / rel.parent
    stem = rel.stem

    if rel.parent.name == stem or rel.suffix != ".py":
        return project_root / rel

    pattern = _infer_folder_pattern(parent_dir)

    flat_candidate = parent_dir / f"{stem}.py"
    if pattern == "module" and not flat_candidate.exists():
        return parent_dir / stem / rel.name
    if pattern == "flat":
        return parent_dir / stem / rel.name

    return project_root / rel


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Helpers – init & stub❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━


def _ensure_init(path: Path, created: List[str]) -> None:
    init_file = path / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Auto-generated by structural workflow\n", encoding="utf-8")
        created.append(str(init_file))


def _build_file_stub(item: PlannedFileCreation, request_id: str) -> str:
    header = f'"""Auto-generated file for {item.path} (request {request_id})."""\n\n'
    deps = f"# dependencies: {', '.join(item.dependencias)}\n\n" if item.dependencias else ""
    sections = [
        f"# section: {sec.name} -> {sec.description}" if isinstance(sec, PlannedFileSection)
        else f"# section: {sec.get('name')} -> {sec.get('description')}"
        for sec in item.secoes
    ]
    return header + deps + "\n".join(sections) + ("\n" if sections else "")


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Função Principal – aplicar plano❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━


def apply_change_plan_to_filesystem(
    root_path: str,
    id_requisicao: str,
    novos_arquivos: List[PlannedFileCreation],
) -> Dict[str, Any]:
    try:
        project_root = Path(root_path)
        created_files: List[str] = []
        skipped: List[str] = []
        touched: set[str] = set()

        add_log("info", f"Applying dynamic plan for {id_requisicao}", "structure_creator")

        for item in novos_arquivos:
            final_path = _materialize_dynamic_path(project_root, item.path)
            final_folder = final_path.parent

            final_folder.mkdir(parents=True, exist_ok=True)
            touched.add(str(final_folder))

            _ensure_init(final_folder, created_files)

            if final_path.exists():
                skipped.append(str(final_path))
                continue

            content = _build_file_stub(item, id_requisicao)
            final_path.write_text(content, encoding="utf-8")
            created_files.append(str(final_path))

        add_log(
            "info",
            f"Dynamic creation done. Files={len(created_files)} skipped={len(skipped)}",
            "structure_creator",
        )

        return {
            "root_path": root_path,
            "created_files": created_files,
            "skipped_existing_files": skipped,
            "touched_dirs": list(touched),
            "message": "Dynamic structure applied successfully.",
        }
    except Exception as e:  # pragma: no cover – fallback
        log_workflow(id_requisicao, f"Erro ao criar estrutura: {e}")
        from utils.path_validation import is_production
        err_msg = "Erro ao criar estrutura." if is_production() else str(e)
        return {"erro": err_msg, "status": "falha"}


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Serviço – Estrutura a partir de relatório❯━━━━━━━━━
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━


def generate_structure_from_report(root_path: str, id_requisicao: str):
    try:
        if not root_path or not str(root_path).strip():
            raise ValueError("root_path é obrigatório para criar estrutura e relatórios no disco.")
        root_path = os.path.normpath(os.path.abspath(str(root_path).strip()))
        reports_dir = os.path.join(root_path, "reports", id_requisicao)
        structure_report_path = os.path.join(reports_dir, "01_structure_report.json")
        if not os.path.exists(structure_report_path):
            raise FileNotFoundError(f"Relatório não encontrado: {structure_report_path}")

        with open(structure_report_path, encoding="utf-8") as f:
            data = json.load(f)

        estrutura = data.get("estrutura_arquivos", {})
        if not estrutura:
            raise ValueError("Relatório de estrutura inválido ou vazio.")

        # Garantir estrutura completa para API (auth_router, auth_service, user_model, settings)
        summary_path = os.path.join(reports_dir, "summary_pipeline.json")
        if os.path.exists(summary_path):
            try:
                with open(summary_path, encoding="utf-8") as sf:
                    summary = json.load(sf)
                refined = (summary.get("refined_prompt") or "").strip()
                if refined:
                    from services.agents.analise_services.structure_service import _ensure_complete_api_structure, _is_api_project
                    if _is_api_project(refined):
                        estrutura = _ensure_complete_api_structure(estrutura, refined)
            except Exception:
                pass

        # --- normalização rápida ---
        normalized: Dict[str, list[str]] = {}
        root_files: list[str] = []
        for key, value in estrutura.items():
            cleaned_key = key.strip().rstrip("/\\")
            if os.path.splitext(cleaned_key)[1] and (not value or not isinstance(value, list)):
                root_files.append(cleaned_key)
            elif os.path.splitext(cleaned_key)[1] and isinstance(value, list) and not value:
                root_files.append(cleaned_key)
            else:
                normalized[cleaned_key] = value
        if root_files:
            normalized[""] = root_files
        estrutura = normalized

        base_dir = os.path.join(root_path, id_requisicao, "generated_code")
        base_dir_abs = os.path.abspath(base_dir)
        os.makedirs(base_dir, exist_ok=True)

        created: Dict[str, list[str]] = {}
        skipped: list[str] = []
        special_files = {".env", "Dockerfile", "Makefile", "docker-compose.yml", "README", "README.md"}

        for folder, files in estrutura.items():
            safe_folder = sanitize_relative_path(str(folder or ".").strip())
            if safe_folder is None:
                add_log("warning", f"structure_creator: folder ignorado (path traversal): {folder}", "structure_creator")
                continue
            folder_path = base_dir if safe_folder == "." else os.path.join(base_dir, safe_folder)
            if not is_path_under_base(os.path.abspath(folder_path), base_dir_abs):
                add_log("warning", f"structure_creator: path fora da base ignorado: {folder}", "structure_creator")
                continue
            if folder and not os.path.exists(folder_path):
                os.makedirs(folder_path, exist_ok=True)

            created[folder or "."] = []
            has_py = any(isinstance(f, str) and f.endswith(".py") for f in files)
            if has_py and folder and "__init__.py" not in files:
                init_path = os.path.join(folder_path, "__init__.py")
                if is_path_under_base(os.path.abspath(init_path), base_dir_abs):
                    with open(init_path, "w", encoding="utf-8") as f:
                        f.write('"""Inicialização do pacote."""\n')
                    created[folder or "."].append("__init__.py")
            for file in files:
                if not isinstance(file, str) or not file or ".." in file or file.startswith("/") or file.startswith("\\"):
                    add_log("warning", f"structure_creator: arquivo ignorado (inseguro): {file}", "structure_creator")
                    continue
                file_path = os.path.join(folder_path, file)
                if not is_path_under_base(os.path.abspath(file_path), base_dir_abs):
                    add_log("warning", f"structure_creator: path fora da base ignorado: {folder}/{file}", "structure_creator")
                    continue
                name, ext = os.path.splitext(file)
                is_file = bool(ext) or file in special_files

                if is_file:
                    if os.path.isdir(file_path):
                        shutil.rmtree(file_path, ignore_errors=True)
                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write("# Arquivo gerado automaticamente\n")
                    created[folder or "."].append(file)
                else:
                    os.makedirs(file_path, exist_ok=True)

        manifest = {
            "id_requisicao": id_requisicao,
            "root_path": base_dir,
            "created": created,
            "skipped": skipped,
            "timestamp": datetime.now().isoformat(),
            "status": "sucesso",
        }

        with open(os.path.join(base_dir, "structure_manifest.json"), "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=4, ensure_ascii=False)

        db_c3.upsert_execution_manifest(id_requisicao, manifest)
        log_workflow(id_requisicao, f"Estrutura criada com sucesso em {base_dir}")
        return manifest

    except Exception as e:  # pragma: no cover
        log_workflow(id_requisicao, f"Erro ao criar estrutura: {e}")
        from utils.path_validation import is_production
        err_msg = "Erro ao criar estrutura." if is_production() else str(e)
        return {"erro": err_msg, "status": "falha"}
