#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Modelos – Code Plan (Compatível com CodePlan Service)❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

from datetime import datetime
from typing import List, Optional, Dict, Any

from pydantic import BaseModel, Field


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Mudança em Arquivo Existente❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

class CodePlanChange(BaseModel):
    """
    Represents a localized modification in an existing file.
    It never contains final code, only a high-level description of the change.
    """

    path: str
    reason: str
    line_start: int
    line_end: int
    current_snippet: str
    new_snippet_description: str


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Blueprint de Novo Arquivo❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

class CodePlanNewFile(BaseModel):
    """
    Represents a new file that must be created.
    It holds only conceptual description and lightweight contracts,
    never full implementation.
    """

    path: str
    reason: str
    content_description: str

    # Hybrid AB – optional micro-contracts per file
    interface: Optional[str] = Field(
        default=None,
        description=(
            "Optional function signature or public API for this file, "
            "for example: `def get_status_payload() -> dict`."
        ),
    )
    test_outline: Optional[str] = Field(
        default=None,
        description=(
            "Optional free-text outline of the main tests that should exist "
            "for this file (unit, contract, etc.)."
        ),
    )
    acceptance_criteria: List[str] = Field(
        default_factory=list,
        description=(
            "Optional structured criteria that describe when this artifact "
            "is considered correct (used to drive test generation)."
        ),
    )


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Artefatos Complementares❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

class CodePlanArtifact(BaseModel):
    """
    Additional artifacts: risks, notes, architectural decisions,
    test plans and any useful metadata.
    """

    type: str
    description: str
    data: Dict[str, Any] = Field(default_factory=dict)


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Documento Completo do Plano de Código❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

class CodePlanDocument(BaseModel):
    """
    Complete document generated by the agent – mirrors exactly
    what the service builds and persists.
    """

    id_requisicao: str
    root_path: str
    prompt_original: str
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    summary: str
    changes_in_existing_files: List[CodePlanChange] = Field(default_factory=list)
    new_files_to_create: List[CodePlanNewFile] = Field(default_factory=list)
    artifacts: List[CodePlanArtifact] = Field(default_factory=list)


#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━
#━━━━━━━━━❮Documento para Persistência no Mongo❯
#━━━━━━━━━━━━━━❮◆❯━━━━━━━━━━━━━━

class CodePlanRecord(BaseModel):
    """
    Record saved into MongoDB – thin wrapper for future evolution.
    """

    id_requisicao: str
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    document: CodePlanDocument
